- name: Check is brew installed
  shell: command -v brew >/dev/null 2>&1
  register: has_brew
  ignore_errors: yes
- name: Install Brew
  block:
    - ansible.builtin.apt:
        name: curl
        state: latest
      become: true
    - file:
        path: brewtmp
        state: directory
    - get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        validate_certs: false
        dest: brewtmp/install_brew.sh
        mode: 0755
    - shell: ./brewtmp/install_brew.sh
    - file:
        path: brewtmp
        state: absent
  when: has_brew.rc > 0
