
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Source linux brew if it is installed
[[ -f /home/linuxbrew/.linuxbrew/bin/brew ]] && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

# PATH
[[ -d $HOME/.local/bin ]] && export PATH="$PATH:$HOME/.local/bin"
