---
- name: Dev Setup
  hosts: all

  tasks:
    - name: include roles for debian
      block:
        - name: include bash
          include_role:
            name: bash
        - name: include vim
          include_role:
            name: vim
        - name: include brew
          include_role:
            name: linuxbrew
        - name: include tmux
          include_role:
            name: tmux
        - name: install lazygit
          homebrew:
            name: lazygit
            state: present
        - name: install direnv
          homebrew:
            name: direnv
            state: present
      when: ansible_facts['os_family']|lower == 'debian'
    - name: include roles for debian
      block:
        - name: include bash
          include_role:
            name: bash
        - name: include bash
          include_role:
            name: tmux
        - name: install lazygit
          homebrew:
            name: lazygit
            state: present
        - name: install direnv
          homebrew:
            name: direnv
            state: present
      when: ansible_facts['os_family']|lower == 'darwin'
